In [36]:
import torch

# 1. 当你设置requires_grad=True后，每次对tensor进行运算，Pytorch都会生成计算图

In [40]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.tensor([1., 2., 3.], device=device,requires_grad=True)
    print(1)
else:
    x = torch.tensor([1., 2., 3.], requires_grad=True)

In [42]:
y = x + 2
print(y)

tensor([3., 4., 5.], grad_fn=<AddBackward0>)


In [43]:
z = y * y * 2
print(z)

tensor([18., 32., 50.], grad_fn=<MulBackward0>)


## 1.2 计算gradient

In [44]:
z = z.mean()
print(z)

tensor(33.3333, grad_fn=<MeanBackward0>)


In [45]:
z.backward()
print(x.grad)

tensor([4.0000, 5.3333, 6.6667])


### 1.2.2 计算gradient--vector

In [47]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = x + 2
z = y * y * 2

In [48]:
z.backward()
z.grad

RuntimeError: grad can be implicitly created only for scalar outputs