In [1]:
import torch

In [3]:
# tensor可以是 1D, 2D, 3D，或者任意维度的
x = torch.ones(2, 2)
print(x.dtype)

torch.float32


In [7]:
# tensor的尺寸
x = torch.ones(2, 2, dtype=torch.float16)
print(x.size())

torch.Size([2, 2])


In [8]:
# python list --> torch.tensor
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# tensor operation

In [13]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.8858, 0.4313],
        [0.1174, 0.2479]])
tensor([[0.1229, 0.4509],
        [0.3847, 0.9082]])


## 1.1 加法

In [16]:
# 加法
z = x + y 
print(z)
z = torch.add(x, y)
print(z)

tensor([[1.0087, 0.8822],
        [0.5020, 1.1561]])
tensor([[1.0087, 0.8822],
        [0.5020, 1.1561]])


In [17]:
# inplace-addition: pytorch中任何有下划线的function，都会做一个inplace-operation
y.add_(x)
print(y)

tensor([[1.0087, 0.8822],
        [0.5020, 1.1561]])


## 1.2 减法

In [22]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.6254, 0.0312],
        [0.9860, 0.5340]])
tensor([[0.7564, 0.7610],
        [0.4530, 0.2232]])


In [23]:
z = x - y
print(z)
z = torch.sub(x, y)
print(z)

tensor([[-0.1310, -0.7298],
        [ 0.5330,  0.3108]])
tensor([[-0.1310, -0.7298],
        [ 0.5330,  0.3108]])


In [24]:
x.sub_(y)
print(x)

tensor([[-0.1310, -0.7298],
        [ 0.5330,  0.3108]])


## 1.3 乘法

In [26]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1440, 0.6400],
        [0.5544, 0.4630]])
tensor([[0.0656, 0.1098],
        [0.9320, 0.1728]])


In [29]:
z = x * y
print(z)
z = torch.mul(x, y)
print(z)

tensor([[0.0094, 0.0702],
        [0.5167, 0.0800]])
tensor([[0.0094, 0.0702],
        [0.5167, 0.0800]])


In [30]:
x.mul_(y)
print(x)

tensor([[0.0094, 0.0702],
        [0.5167, 0.0800]])


## 1.4 除法

In [32]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.2252, 0.3374],
        [0.9898, 0.6821]])
tensor([[0.0719, 0.8606],
        [0.2653, 0.8219]])


In [33]:
z = x / y
print(z)
z = torch.div(x, y)
print(z)

tensor([[3.1303, 0.3921],
        [3.7313, 0.8299]])
tensor([[3.1303, 0.3921],
        [3.7313, 0.8299]])


In [34]:
x.div_(y)
print(x)

tensor([[3.1303, 0.3921],
        [3.7313, 0.8299]])


# 2. Index or Slice

## 2.1 Index or Slice

In [37]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0396, 0.6591, 0.1269],
        [0.4136, 0.9852, 0.8125],
        [0.8344, 0.0076, 0.6598],
        [0.7111, 0.5768, 0.9536],
        [0.0540, 0.7112, 0.2756]])


In [38]:
print(x[:, 0])

tensor([0.0396, 0.4136, 0.8344, 0.7111, 0.0540])


In [41]:
print(x[1, 1])
# if tensor内只有一个element，tensor.item()得到该element
print(x[1, 1].item())

tensor(0.9852)
0.9851770997047424


## 2.2 flatten

In [42]:
x = torch.rand(4, 4)
print(x)

tensor([[0.8265, 0.7977, 0.5233, 0.8930],
        [0.1072, 0.2398, 0.5827, 0.9748],
        [0.4974, 0.9226, 0.6705, 0.3471],
        [0.4521, 0.8347, 0.6577, 0.3219]])


In [45]:
# return (1, 16)
y = x.view(16)
print(y)

tensor([0.8265, 0.7977, 0.5233, 0.8930, 0.1072, 0.2398, 0.5827, 0.9748, 0.4974,
        0.9226, 0.6705, 0.3471, 0.4521, 0.8347, 0.6577, 0.3219])


In [47]:
# return (2, 8)
y = x.view(-1, 8)
print(y)

tensor([[0.8265, 0.7977, 0.5233, 0.8930, 0.1072, 0.2398, 0.5827, 0.9748],
        [0.4974, 0.9226, 0.6705, 0.3471, 0.4521, 0.8347, 0.6577, 0.3219]])


# 3. numpy

In [48]:
import numpy as np

## 3.1 torch.tensor --> numpy.array

In [53]:
# torch.tensor --> numpy.array
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [54]:
# 如果在CPU上运行，上面两者共享内存，改变一个，另一个也发生改变
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## 3.2 numpy.array --> torch.tensor

In [55]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>


## 3.3 在cuda上生成tensor

In [56]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    # you can create it so simply by saying followings:
    y = torch.ones(5)
    y = y.to(device)
    # Do an operation on GPU, will be much faster
    z = x + y
    
    # following statement will call a error, because tensor.numpy only work on CPU, 
    # cannot convert a GPU tensor to numpy.array
    # if we want to do this(tensor --> numpy), we should move it back to CPU
    z.numpy()
    
    z = z.to("cpu")
    z.numpy()

# 4. Calculate gradient for tensor

In [58]:
# it means it will calculate the gradient for this tensor later in your optimization steps(SGD)
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
