In [1]:
import torch

In [2]:
x = torch.empty(2, 3)
print(x)

tensor([[4.4650e+30, 7.0975e+22, 7.9309e+34],
        [7.9439e+08, 3.2604e-12, 7.3113e+34]])


In [3]:
x = torch.rand(2, 2)
print(x)

tensor([[0.8471, 0.3351],
        [0.7820, 0.0604]])


In [4]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
x = torch.ones(2, 2, dtype=torch.float32)
print(x)

print(x.size())     # type = torch.Size

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [10]:
x = torch.rand(2, 2, dtype=torch.float32)
y = torch.rand(2, 2, dtype=torch.float32)

z = x + y
print(z)
print(z[:, 1])  # 取出后成一维数组

tensor([[1.6163, 1.1263],
        [1.6266, 0.9452]])
tensor([1.1263, 0.9452])


In [11]:
x = torch.rand(5, 3)
print(x[1, 1].item())   # 取出一个数

0.3719552159309387


In [16]:
x = torch.rand(4, 4)
y = x.view(2, 2, 4)

print(x.size())
print(y.size())

torch.Size([4, 4])
torch.Size([2, 2, 4])


In [19]:
import numpy as np
import torch

In [30]:
a = torch.ones(5, dtype=torch.float64)
print(type(a), a)
b = a.numpy()
print(type(b), b)

<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]


In [31]:
a = np.ones(5, dtype=np.float64)
print(type(a), a)
b = torch.from_numpy(a)
print(type(b), b)

<class 'numpy.ndarray'> [1. 1. 1. 1. 1.]
<class 'torch.Tensor'> tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
import torch


if torch.cuda.is_available():
    device = torch.device("cuda")
    # Create a tensor on GPU
    x = torch.ones(5, device=device)

    # Create a tensor on CPU
    y = torch.ones(5)
    # And then move this tensor to GPU
    y = y.to(device)

    # This operatiom will perform on GPU
    z = x + y

    # Error: numpy can only handle CPU data
    z.numpy()
    print(z)

    # 将 z 从 GPU 移动到 CPU
    z.to("cpu")
    print()