In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda:0")

In [21]:
x = torch.tensor(
            [4],
            dtype=torch.float32,
            requires_grad=True,
            )
print(x)

tensor([4.], requires_grad=True)


In [22]:
y = x ** 2
print(y)

tensor([16.], grad_fn=<PowBackward0>)


In [23]:
y.backward()
x.grad

tensor([8.])